name: Tag and Update Version

on:
  push:
    branches:
    - master
    paths-ignore:
    - 'README.md'
    - '.github/**'
env:
  SERVICE_NAME: ${{ github.event.repository.name }}
jobs:
  tag-build-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout current code
      uses: actions/checkout@master
    - name: Bump version and push tag
      id: tag
      uses: broadinstitute/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: false
    - name: Update Framework Version Mapping
      uses: broadinstitute/repository-dispatch@master
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: databiosphere/framework-version
        event-type: version-bump
        client-payload: '{"service": "${{ env.SERVICE_NAME }}", "version": "${{ steps.tag.outputs.tag }}"}'
